### ISSUE TITLE
Failed to find share dir for dist 'Alien-CSFML'

### ISSUE THREAD

**Issue by eserte** [sanko/alien-csfml#1]
The test suite fails on all of my smoker systems:
```
Failed to find share dir for dist 'Alien-CSFML' at /usr/home/cpansand/.cpan/build/2022102103/Alien-CSFML-v0.0.3-3/blib/lib/Alien/CSFML.pm line 18.
t/0002_c_exe.t .... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Failed to find share dir for dist 'Alien-CSFML' at /usr/home/cpansand/.cpan/build/2022102103/Alien-CSFML-v0.0.3-3/blib/lib/Alien/CSFML.pm line 18.
t/0003_cxx_exe.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by sanko** [comment]
I saw all the failures but I haven't attempted to diagnose it yet. The smokers are eating the output of `./Build` step which is mostly just `system(...)` calls to `cmake` and and continuing anyway. It's probably a missing lib dependency so I'll exit based on the value of `$?`.

**Comment by eserte** [comment]
The last commit will not improve things --- actually you only handle completely failed system calls (-1) and signal aborts, but not normal command failures ($? != 0).

**Comment by sanko** [comment]
I was hoping to just get the error code printed but since it's eating the build step output, you're right.

But honestly, smoke testing is such a black box vs Github Actions or local CI that I'm not even sure if it's worth the effort to try and resolve this yet (my goal is to wrap SFML with FFI but that's weeks away or longer). I could try building small examples that link to the various dependencies one by one to see where it fails (which cmake already does, of course) but, again, the output of `./Build` isn't passed along in reports so I'd still have no idea...

**Comment by eserte** [comment]
If Build itself fails, then it *is* passed along. So just do a `die if $? != 0` or so...

**Comment by eserte** [comment]
With the newest version build fail reports are generated. CPAN Testers is somewhat slow to be delivered at the end, but here some snippets from my systems:

fbsd13:
```
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenAL (missing: OPENAL_LIBRARY OPENAL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindOpenAL.cmake:90 (find_package_handle_standard_args)
  /var/tmp/cpansmoker-1023/2022102118/EZuALl1acR/build/sfml/_deps/sfml-src/cmake/Macros.cmake:391 (find_package)
  /var/tmp/cpansmoker-1023/2022102118/EZuALl1acR/build/sfml/_deps/sfml-src/src/SFML/Audio/CMakeLists.txt:71 (sfml_find_package)
```

fbsd14:
```
CMake Error at /usr/perl5.34.0p/lib/site_perl/5.34.0/amd64-freebsd/auto/share/dist/Alien-cmake3/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/perl5.34.0p/lib/site_perl/5.34.0/amd64-freebsd/auto/share/dist/Alien-cmake3/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/perl5.34.0p/lib/site_perl/5.34.0/amd64-freebsd/auto/share/dist/Alien-cmake3/share/cmake-3.21/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /var/tmp/cpansmoker-1023/2022102118/SHeD1oI72Z/build/sfml/_deps/sfml-src/cmake/Macros.cmake:391 (find_package)
  /var/tmp/cpansmoker-1023/2022102118/SHeD1oI72Z/build/sfml/_deps/sfml-src/src/SFML/Window/CMakeLists.txt:325 (sfml_find_package)
```

fedora linux 36:
```
CMake Error at /var/tmp/cpansmoker-1023/2022102118/VLrQH1fXY1/build/sfml/_deps/sfml-src/cmake/Modules/FindUDev.cmake:49 (MESSAGE):
  Could not find UDev library
Call Stack (most recent call first):
  /var/tmp/cpansmoker-1023/2022102118/VLrQH1fXY1/build/sfml/_deps/sfml-src/cmake/Macros.cmake:391 (find_package)
  /var/tmp/cpansmoker-1023/2022102118/VLrQH1fXY1/build/sfml/_deps/sfml-src/src/SFML/Window/CMakeLists.txt:338 (sfml_find_package)
```

**Comment by sanko** [comment]
Yeah, I assumed they'd be the same as the results for the original Alien::SFML. Just missing the dependencies I documented a few days ago in POD.

**Comment by eserte** [comment]
From my point of view this issue may be closed as the report result turned from a FAIL into an UNKNOWN.

**Comment by sanko** [comment]
Same.

Traded a red matrix page in for a yellow one. :)
